project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning"
  sidebar:
    background: primary
    # logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/chefs-kiss/ML_J2026
        text: GitHub
    style: docked
    contents:
    - section: "Course Information"
      contents:
        - href: index.qmd
          text: Home
        - href: course_information/schedule.qmd
          text: Schedule
        - href: https://mdl.stolaf.edu/mod/forum/view.php?id=514243
          text: Moodle Forum
    - section: "Materials"
      contents:
        - href: homework.qmd
          text: Homework
        - href: labs.qmd
          text: Labs
        - href: project.qmd
          text: Project
        - href: slides.qmd
          text: Slides
        - href: articles.qmd
          text: Article Reviews

format:
  html:
    theme: lux #vapor
    # css: styles.css
    toc: true

execute:
  freeze: auto

